# Generated by Django 2.1.1 on 2018-09-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='active',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
