# Generated by Django 2.1.1 on 2018-09-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculer', '0002_workbook_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_workbook', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='workbook',
            name='active',
        ),
    ]
